const GOLDEN_RATIO = 1.618;

const TITLE_SIZE = 55;
const SUBTITLE_SIZE = TITLE_SIZE / GOLDEN_RATIO;
const HEADING_SIZE = SUBTITLE_SIZE / GOLDEN_RATIO;
const BODY_SIZE = HEADING_SIZE / GOLDEN_RATIO;
const BODY2_SIZE = BODY_SIZE / GOLDEN_RATIO;

export const FONT_SIZES = [
  `${TITLE_SIZE}pt`,
  `${SUBTITLE_SIZE}pt`,
  `${HEADING_SIZE}pt`,
  `${BODY_SIZE}pt`,
  `${BODY2_SIZE}pt`,
];
